### PR TITLE
Fix WorldGuard region checking

### PR DESCRIPTION
**Pull request by MegaNarwhal**
Make region checking code much more readable and make geSuitTeleports actually load after WorldGuard if it's present.

### CODE REVIEW

**Comment by Narimm** [comment]
Sorry this commit reverses things we added for our own purposes and adds a geSuit Spawn dep that is unnecessary...
We dont need extra log messages.

I am not sure what you have actually added in this PR.

**Comment by Narimm** [comment]
Actually sorry, I am closing the PR.

But a piece of advice if you dont have a dependency you can assume that other people who build it do if they build successfully.  The best way to resolve them is to ask.  Most likely we just havent pushed the dep to our repo maven.addstar.com.au. Which we can do if you ask :) 

Aside from that the region checking is designed to make sure people are not able to tp into regions that are marked as disallowing TP's.

**Comment by MegaNarwhal** [comment]
@Narimm This makes WorldGuard hook properly (region checking was completely disabled before fixing the plugin.yml), makes the checking code far more readable, and makes the console output more concise and understandable. It preserves the intended functionality, unless interfering with teleports that should probably not be interfered with (e.g. command blocks) is intended. I know adding the geSuitSpawn.jar to the repo is neither ideal nor a permanent solution but as you mentioned, there was/is no proper repo to get it from and at least it allows this to compile without any changes necessary for those who might want to contribute to this repo.

**Comment by alchemistmatt** [comment]
We now have geSuitSpawn in our artifactory repository; see commit cba7d4cf6e50efbc70fa854812

**Pull request closed without merging**
